/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface TinalstHearder {
      'first': string;
      'last': string;
    }
  }

  interface HTMLTinalstHearderElement extends StencilComponents.TinalstHearder, HTMLStencilElement {}

  var HTMLTinalstHearderElement: {
    prototype: HTMLTinalstHearderElement;
    new (): HTMLTinalstHearderElement;
  };
  interface HTMLElementTagNameMap {
    'tinalst-hearder': HTMLTinalstHearderElement;
  }
  interface ElementTagNameMap {
    'tinalst-hearder': HTMLTinalstHearderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'tinalst-hearder': JSXElements.TinalstHearderAttributes;
    }
  }
  namespace JSXElements {
    export interface TinalstHearderAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;